#!/usr/bin/env python3
"""Generate and verify the Markdown configuration catalog from `src/shared/env.py`.

CONFIG_FIELDS in src/shared/env.py is the one declarative catalog of user-settable config vars
(key, secret, group, default, description). This script renders grouped Markdown tables for
the canonical configuration reference. Overview docs intentionally list only common settings.

Usage:
    python3 scripts/gen_env_docs.py                 # print the generated catalog block
    python3 scripts/gen_env_docs.py --write FILE…   # replace the generated block in each file
    python3 scripts/gen_env_docs.py --check FILE…   # fail if a generated block is stale

Stdlib-only; reads CONFIG_FIELDS via `ast` (no import of shared.env, no side effects).
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PY = REPO_ROOT / "src" / "shared" / "env.py"
# (key, secret, group, default, description) — mirrors the CONFIG_FIELDS comment in env.py.
Field = tuple[str, bool, str, str, str]
BEGIN_MARKER = "<!-- BEGIN GENERATED CONFIG CATALOG -->"
END_MARKER = "<!-- END GENERATED CONFIG CATALOG -->"


def load_config_fields(path: Path = ENV_PY) -> list[Field]:
    """Extract the literal CONFIG_FIELDS list from env.py without importing it."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            targets, value = node.targets, node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            targets, value = [node.target], node.value
        else:
            continue
        for target in targets:
            if isinstance(target, ast.Name) and target.id == "CONFIG_FIELDS":
                fields = ast.literal_eval(value)
                if not isinstance(fields, list):
                    raise SystemExit(f"error: CONFIG_FIELDS in {path} is not a list literal")
                return fields
    raise SystemExit(f"error: CONFIG_FIELDS not found in {path}")


def render(fields: list[Field]) -> str:
    """Render CONFIG_FIELDS as one Markdown table per group, in catalog order."""
    lines = [
        BEGIN_MARKER,
        "<!-- Generated by scripts/gen_env_docs.py from src/shared/env.py CONFIG_FIELDS. -->",
    ]
    current_group = None
    for key, secret, group, default, description in fields:
        if group != current_group:
            lines += ["", f"### {group}", "", "| Variable | Default | Purpose |", "|---|---|---|"]
            current_group = group
        purpose = f"{description} *(secret)*" if secret else description
        lines.append(f"| `{key}` | {default or '—'} | {purpose} |")
    lines += ["", END_MARKER]
    return "\n".join(lines) + "\n"


def check(fields: list[Field], doc_paths: list[Path]) -> int:
    """Verify each document contains the exact current generated block."""
    status = 0
    expected = render(fields).rstrip("\n")
    for doc in doc_paths:
        if not doc.is_file():
            print(f"error: {doc}: file not found", file=sys.stderr)
            status = 1
            continue
        text = doc.read_text(encoding="utf-8")
        start = text.find(BEGIN_MARKER)
        end = text.find(END_MARKER, start + len(BEGIN_MARKER)) if start >= 0 else -1
        actual = text[start : end + len(END_MARKER)] if end >= 0 else ""
        if actual != expected:
            print(
                f"error: {doc.relative_to(REPO_ROOT) if doc.is_relative_to(REPO_ROOT) else doc}: "
                "generated configuration catalog is missing or stale; run "
                f"`python3 scripts/gen_env_docs.py --write {doc}`",
                file=sys.stderr,
            )
            status = 1
        else:
            print(
                f"ok: {doc.relative_to(REPO_ROOT) if doc.is_relative_to(REPO_ROOT) else doc}: "
                f"generated catalog matches all {len(fields)} CONFIG_FIELDS entries"
            )
    return status


def write(fields: list[Field], doc_paths: list[Path]) -> int:
    """Replace the marked generated block in each document."""
    status = 0
    replacement = render(fields).rstrip("\n")
    for doc in doc_paths:
        if not doc.is_file():
            print(f"error: {doc}: file not found", file=sys.stderr)
            status = 1
            continue
        text = doc.read_text(encoding="utf-8")
        start = text.find(BEGIN_MARKER)
        end = text.find(END_MARKER, start + len(BEGIN_MARKER)) if start >= 0 else -1
        if end < 0:
            print(f"error: {doc}: generated catalog markers not found", file=sys.stderr)
            status = 1
            continue
        end += len(END_MARKER)
        doc.write_text(text[:start] + replacement + text[end:], encoding="utf-8")
        print(f"updated: {doc.relative_to(REPO_ROOT) if doc.is_relative_to(REPO_ROOT) else doc}")
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        nargs="+",
        metavar="FILE",
        default=None,
        help="verify each FILE contains the exact generated CONFIG_FIELDS catalog",
    )
    mode.add_argument(
        "--write",
        nargs="+",
        metavar="FILE",
        default=None,
        help="replace the generated CONFIG_FIELDS catalog in each FILE",
    )
    args = parser.parse_args(argv)

    fields = load_config_fields()
    if args.check is None and args.write is None:
        sys.stdout.write(render(fields))
        return 0
    paths = args.check if args.check is not None else args.write
    docs = [Path(p).resolve() for p in paths]
    return check(fields, docs) if args.check is not None else write(fields, docs)


if __name__ == "__main__":
    raise SystemExit(main())
