"""MCP tool: import an asset generated by Hyper3D Rodin into the Blender scene."""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class ImportGeneratedAssetArgs(BaseModel):
    name: str
    task_uuid: Optional[str] = None
    request_id: Optional[str] = None


TOOL = {"name": "import_generated_asset", "args": ImportGeneratedAssetArgs}


def handle(arguments: dict[str, Any]) -> list[dict[str, Any]]:
    """Import the asset generated by Hyper3D Rodin after the generation task is completed. Only give
    one of {task_uuid, request_id} based on the Hyper3D Rodin Mode. Returns whether the asset has
    been imported successfully.

    Args:
        name: The name of the object in scene.
        task_uuid: For Hyper3D Rodin mode MAIN_SITE: the task_uuid given in the generate model step.
        request_id: For Hyper3D Rodin mode FAL_AI: the request_id given in the generate model step.
    """
    import json

    from qwen_mm_plugins_blender.loader import get_connection

    name = arguments.get("name", "")
    task_uuid = arguments.get("task_uuid", None)
    request_id = arguments.get("request_id", None)
    try:
        kwargs = {"name": name}
        if task_uuid:
            kwargs["task_uuid"] = task_uuid
        elif request_id:
            kwargs["request_id"] = request_id
        result = get_connection().send_command("import_generated_asset", kwargs)
        return [{"type": "text", "text": json.dumps(result, indent=2)}]
    except Exception as e:
        return [{"type": "text", "text": f"Error generating Hyper3D task: {e}"}]
