"""MCP tool: import an asset generated by Hunyuan3D into Blender."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class ImportGeneratedAssetHunyuanArgs(BaseModel):
    name: str
    zip_file_url: str


TOOL = {"name": "import_generated_asset_hunyuan", "args": ImportGeneratedAssetHunyuanArgs}


def handle(arguments: dict[str, Any]) -> list[dict[str, Any]]:
    """Import the asset generated by Hunyuan3D after the generation task is completed. Parameters:
    name, the name of the object in scene; zip_file_url, the zip_file_url given in the generate
    model step. Returns whether the asset has been imported successfully.

    Args:
        name: The name of the object in scene.
        zip_file_url: The zip_file_url given in the generate model step.
    """
    import json

    from qwen_mm_plugins_blender.loader import get_connection

    name = arguments.get("name")
    zip_file_url = arguments.get("zip_file_url")
    try:
        kwargs = {
            "name": name,
        }
        if zip_file_url:
            kwargs["zip_file_url"] = zip_file_url
        result = get_connection().send_command("import_generated_asset_hunyuan", kwargs)
        return [{"type": "text", "text": json.dumps(result, indent=2)}]
    except Exception as e:
        return [{"type": "text", "text": f"Error generating Hunyuan3D task: {str(e)}"}]
